language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7
  - 7.1
  - hhvm-3.12

install:
    - composer install -n

script:
    - php vendor/bin/php-cs-fixer fix lib --diff --level=psr2 --dry-run -v
    - php vendor/bin/phpunit
